In [ ]:
pip install pandas

In [31]:
import pandas as pd
pd.set_option('display.max_rows', None)

# df = pd.read_csv('CA006158731.csv.gz', header = None)  
# print(df.head(10))
# print(df.info()

In [32]:
base_url = "https://www.ncei.noaa.gov/pub/data/ghcn/daily/"
daily_obs_path = "by_station/"
toronto_file = "CA006158731.csv.gz" 
montreal_file = "CA007025251.csv.gz"
vancouver_file = "CA001108395.csv.gz"
calgary_file = "CA003031092.csv.gz"
ottawa_file = "CA006106001.csv.gz"

cities_list = [toronto_file, montreal_file, vancouver_file, calgary_file, ottawa_file]

station_metadata = "ghcnd-stations.txt"
station_inventory = "ghcnd-inventory.txt"
country_codes = "ghcnd-countries.txt"
data_dictionary = "readme.txt"

# Stations Data

In [33]:
toronto_file = "CA006158731.csv.gz" 
toronto_df = pd.read_csv(f"{base_url}{daily_obs_path}{toronto_file}", compression="gzip", header=None)
columns_dict = {0:"ID", 1:"DATE", 2:"ELEMENT", 3:"DATA_VALUE", 4:"M-FLAG", 5:"Q-FLAG", 6:"S-FLAG", 7:"OBS-TIME"}
toronto_df.rename(columns=columns_dict, inplace = True)
toronto_df.info()
toronto_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 25944 entries, 0 to 25943
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          25944 non-null  str
 1   DATE        25944 non-null  int64
 2   ELEMENT     25944 non-null  str
 3   DATA_VALUE  25944 non-null  int64
 4   M-FLAG      1147 non-null   str
 5   Q-FLAG      3 non-null      str
 6   S-FLAG      25944 non-null  str
 7   OBS-TIME    0 non-null      float64
dtypes: float64(1), int64(2), str(5)
memory usage: 1.6 MB

            ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  OBS-TIME
0  CA006158731  20130613    TMAX         227    NaN    NaN      C       NaN
1  CA006158731  20130614    TMAX         226    NaN    NaN      C       NaN
2  CA006158731  20130615    TMAX         258    NaN    NaN      C       NaN
3  CA006158731  20130616    TMAX         261    NaN    NaN      C       NaN
4  CA006158731  20130617    TMAX         247    NaN    NaN      C       NaN

In [5]:
toronto_df[toronto_df["Q-FLAG"].notna()]

,ID,DATE,ELEMENT,DATA_VALUE,M-FLAG,Q-FLAG,S-FLAG,OBS-TIME
11085,CA006158731,20180504,WSFG,1190,NaN,X,C,NaN
18712,CA006158731,20210528,SNOW,2,NaN,O,C,NaN
21250,CA006158731,20220521,WSFG,1210,NaN,X,C,NaN

In [6]:
toronto_df["ELEMENT"].unique()
# TMAX = Maximum temperature (tenths of degrees C)
# TMIN = Minimum temperature (tenths of degrees C)
# PRCP = Precipitation (tenths of mm)
#    	   SNOW = Snowfall (mm)
# 	   SNWD = Snow depth (mm)
# TAVG = Average daily temperature (tenths of degrees C)
# 	          [Note that TAVG from source 'S' corresponds
# 		   to an average of hourly readings for the period
# 		   ending at 2400 UTC rather than local midnight or other
#                    Local Standard Time according to a specific 
#                    Met Service's protocol]
#                   [For sources other than 'S' TAVG is computed in a 
#                    variety of ways including
#                    traditional fixed hours of the day whereas TAXN
#                   is solely computed as (TMAX+TMIN)/2.0]
# WDFG = Direction of peak wind gust (degrees)
# WSFG = Peak gust wind speed (tenths of meters per second)

<StringArray>
['TMAX', 'TMIN', 'PRCP', 'SNOW', 'SNWD', 'TAVG', 'WDFG', 'WSFG']
Length: 8, dtype: str

In [7]:
# toronto_file = "CA006158731.csv.gz" 
montreal_df = pd.read_csv(f"{base_url}{daily_obs_path}{montreal_file}", compression="gzip", header=None)
# columns_dict = {0:"ID", 1:"DATE", 2:"ELEMENT", 3:"DATA_VALUE", 4:"M-FLAG", 5:"Q-FLAG", 6:"S-FLAG", 7:"OBS-TIME"}
montreal_df.rename(columns=columns_dict, inplace = True)
montreal_df.info()
montreal_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 26415 entries, 0 to 26414
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          26415 non-null  str
 1   DATE        26415 non-null  int64
 2   ELEMENT     26415 non-null  str
 3   DATA_VALUE  26415 non-null  int64
 4   M-FLAG      1206 non-null   str
 5   Q-FLAG      1 non-null      str
 6   S-FLAG      26415 non-null  str
 7   OBS-TIME    0 non-null      float64
dtypes: float64(1), int64(2), str(5)
memory usage: 1.6 MB

            ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  OBS-TIME
0  CA007025251  20130218    TMAX         -81    NaN    NaN      C       NaN
1  CA007025251  20130219    TMAX          -1    NaN    NaN      C       NaN
2  CA007025251  20130220    TMAX         -10    NaN    NaN      C       NaN
3  CA007025251  20130221    TMAX         -59    NaN    NaN      C       NaN
4  CA007025251  20130223    TMAX          13    NaN    NaN      C       NaN

In [8]:
vancouver_df = pd.read_csv(f"{base_url}{daily_obs_path}{vancouver_file}", compression="gzip", header=None)
# columns_dict = {0:"ID", 1:"DATE", 2:"ELEMENT", 3:"DATA_VALUE", 4:"M-FLAG", 5:"Q-FLAG", 6:"S-FLAG", 7:"OBS-TIME"}
vancouver_df.rename(columns=columns_dict, inplace = True)
vancouver_df.info()
vancouver_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 72041 entries, 0 to 72040
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          72041 non-null  str
 1   DATE        72041 non-null  int64
 2   ELEMENT     72041 non-null  str
 3   DATA_VALUE  72041 non-null  int64
 4   M-FLAG      16721 non-null  str
 5   Q-FLAG      8 non-null      str
 6   S-FLAG      72041 non-null  str
 7   OBS-TIME    0 non-null      float64
dtypes: float64(1), int64(2), str(5)
memory usage: 4.4 MB

/var/folders/1f/sv9398xj4s35n39r0h5cb4580000gp/T/ipykernel_39799/1763519183.py:1: DtypeWarning: Columns (0: 5) have mixed types. Specify dtype option on import or set low_memory=False.
  vancouver_df = pd.read_csv(f"{base_url}{daily_obs_path}{vancouver_file}", compression="gzip", header=None)

            ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  OBS-TIME
0  CA001108395  19570107    TMAX          56    NaN    NaN      S       NaN
1  CA001108395  19570108    TMAX          56    NaN    NaN      S       NaN
2  CA001108395  19570109    TMAX          28    NaN    NaN      S       NaN
3  CA001108395  19570106    TMIN           6    NaN    NaN      S       NaN
4  CA001108395  19570107    TMIN          11    NaN    NaN      S       NaN

In [9]:
calgary_df = pd.read_csv(f"{base_url}{daily_obs_path}{calgary_file}", compression="gzip", header=None)
# columns_dict = {0:"ID", 1:"DATE", 2:"ELEMENT", 3:"DATA_VALUE", 4:"M-FLAG", 5:"Q-FLAG", 6:"S-FLAG", 7:"OBS-TIME"}
calgary_df.rename(columns=columns_dict, inplace = True)
calgary_df.info()
calgary_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 27457 entries, 0 to 27456
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          27457 non-null  str
 1   DATE        27457 non-null  int64
 2   ELEMENT     27457 non-null  str
 3   DATA_VALUE  27457 non-null  int64
 4   M-FLAG      1136 non-null   str
 5   Q-FLAG      35 non-null     str
 6   S-FLAG      27457 non-null  str
 7   OBS-TIME    0 non-null      float64
dtypes: float64(1), int64(2), str(5)
memory usage: 1.7 MB

            ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  OBS-TIME
0  CA003031092  20120712    TMAX         273    NaN    NaN      C       NaN
1  CA003031092  20120713    TMAX         256    NaN    NaN      C       NaN
2  CA003031092  20120714    TMAX         214    NaN    NaN      C       NaN
3  CA003031092  20120715    TMAX         184    NaN    NaN      C       NaN
4  CA003031092  20120716    TMAX         194    NaN    NaN      C       NaN

In [10]:
ottawa_df = pd.read_csv(f"{base_url}{daily_obs_path}{ottawa_file}", compression="gzip", header=None)
# columns_dict = {0:"ID", 1:"DATE", 2:"ELEMENT", 3:"DATA_VALUE", 4:"M-FLAG", 5:"Q-FLAG", 6:"S-FLAG", 7:"OBS-TIME"}
ottawa_df.rename(columns=columns_dict, inplace = True)
ottawa_df.info()
ottawa_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 28444 entries, 0 to 28443
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          28444 non-null  str
 1   DATE        28444 non-null  int64
 2   ELEMENT     28444 non-null  str
 3   DATA_VALUE  28444 non-null  int64
 4   M-FLAG      1277 non-null   str
 5   Q-FLAG      4 non-null      str
 6   S-FLAG      28444 non-null  str
 7   OBS-TIME    0 non-null      float64
dtypes: float64(1), int64(2), str(5)
memory usage: 1.7 MB

            ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  OBS-TIME
0  CA006106001  20111215    TMAX         104    NaN    NaN      C       NaN
1  CA006106001  20111216    TMAX          67    NaN    NaN      C       NaN
2  CA006106001  20111217    TMAX         -65    NaN    NaN      C       NaN
3  CA006106001  20111218    TMAX         -53    NaN    NaN      C       NaN
4  CA006106001  20111219    TMAX          51    NaN    NaN      C       NaN

In [14]:
print(sorted(toronto_df["ELEMENT"].unique()))
print(sorted(montreal_df["ELEMENT"].unique()))
print(sorted(vancouver_df["ELEMENT"].unique()))
print(sorted(calgary_df["ELEMENT"].unique()))
print(sorted(ottawa_df["ELEMENT"].unique()))

['PRCP', 'SNOW', 'SNWD', 'TAVG', 'TMAX', 'TMIN', 'WDFG', 'WSFG']
['PRCP', 'SNOW', 'SNWD', 'TAVG', 'TMAX', 'TMIN', 'WDFG', 'WSFG']
['PRCP', 'SNOW', 'SNWD', 'TAVG', 'TMAX', 'TMIN', 'WDFG', 'WSFG']
['PRCP', 'SNOW', 'SNWD', 'TAVG', 'TMAX', 'TMIN', 'WDFG', 'WSFG']
['PRCP', 'SNOW', 'SNWD', 'TAVG', 'TMAX', 'TMIN', 'WDFG', 'WSFG']

In [ ]:
sorted(toronto_df["ELEMENT"].unique())

# TMAX = Maximum temperature (tenths of degrees C) -> transform
# TMIN = Minimum temperature (tenths of degrees C) -> transform
# PRCP = Precipitation (tenths of mm) -> transform
# SNOW = Snowfall (mm)
# SNWD = Snow depth (mm)
# TAVG = Average daily temperature (tenths of degrees C) -> transform
# 	          [Note that TAVG from source 'S' corresponds
# 		   to an average of hourly readings for the period
# 		   ending at 2400 UTC rather than local midnight or other
#                    Local Standard Time according to a specific 
#                    Met Service's protocol]
#                   [For sources other than 'S' TAVG is computed in a 
#                    variety of ways including
#                    traditional fixed hours of the day whereas TAXN
#                   is solely computed as (TMAX+TMIN)/2.0]
# WDFG = Direction of peak wind gust (degrees)
# WSFG = Peak gust wind speed (tenths of meters per second) -> transform

['PRCP', 'SNOW', 'SNWD', 'TAVG', 'TMAX', 'TMIN', 'WDFG', 'WSFG']

In [35]:
toronto_df[toronto_df['ELEMENT']=='TAVG'].head(10)

               ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  OBS-TIME
2950  CA006158731  20150401    TAVG          16    NaN    NaN      C       NaN
2951  CA006158731  20150402    TAVG         100    NaN    NaN      C       NaN
2952  CA006158731  20150403    TAVG          82    NaN    NaN      C       NaN
2953  CA006158731  20150404    TAVG          16    NaN    NaN      C       NaN
2954  CA006158731  20150405    TAVG          -5    NaN    NaN      C       NaN
2955  CA006158731  20150406    TAVG          46    NaN    NaN      C       NaN
2956  CA006158731  20150407    TAVG          44    NaN    NaN      C       NaN
2957  CA006158731  20150408    TAVG          27    NaN    NaN      C       NaN
2958  CA006158731  20150409    TAVG          50    NaN    NaN      C       NaN
2959  CA006158731  20150410    TAVG         103    NaN    NaN      C       NaN

In [ ]:
toronto_df[toronto_df['ELEMENT']=='TMIN'].head(10)

In [ ]:
toronto_df[toronto_df['ELEMENT']=='TMAX'].head(10)

In [31]:
print(f"TORONTO: {toronto_df['Q-FLAG'].value_counts(dropna=False)}\n")
print(f"MONTREAL: {montreal_df['Q-FLAG'].value_counts(dropna=False)}\n")
print(f"VANCOUVER: {vancouver_df['Q-FLAG'].value_counts(dropna=False)}\n")
print(f"CALGARY: {calgary_df['Q-FLAG'].value_counts(dropna=False)}\n")
print(f"OTTAWA: {ottawa_df['Q-FLAG'].value_counts(dropna=False)}\n")

TORONTO: Q-FLAG
NaN    25941
X          2
O          1
Name: count, dtype: int64

MONTREAL: Q-FLAG
NaN    26414
X          1
Name: count, dtype: int64

VANCOUVER: Q-FLAG
NaN    72033
O          5
S          1
G          1
M          1
Name: count, dtype: int64

CALGARY: Q-FLAG
NaN    27422
I         35
Name: count, dtype: int64

OTTAWA: Q-FLAG
NaN    28440
I          3
X          1
Name: count, dtype: int64

Q-FLAG
NaN    25941
X          2
O          1
Name: count, dtype: int64

In [13]:
print(toronto_df[toronto_df["Q-FLAG"].notna()])
print(montreal_df[montreal_df["Q-FLAG"].notna()])
print(vancouver_df[vancouver_df["Q-FLAG"].notna()])
print(calgary_df[calgary_df["Q-FLAG"].notna()])
print(ottawa_df[ottawa_df["Q-FLAG"].notna()])

                ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  \
11085  CA006158731  20180504    WSFG        1190    NaN      X      C
18712  CA006158731  20210528    SNOW           2    NaN      O      C
21250  CA006158731  20220521    WSFG        1210    NaN      X      C

       OBS-TIME
11085       NaN
18712       NaN
21250       NaN
                ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  \
11562  CA007025251  20180504    WSFG        1170    NaN      X      C

       OBS-TIME
11562       NaN
                ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  \
8104   CA001108395  19820119    PRCP        1113    NaN      S      S
12989  CA001108395  19851127    TMAX         -77    NaN      O      S
17363  CA001108395  19890413    SNWD         691    NaN      G      S
30188  CA001108395  19990928    SNWD          10    NaN      O      S
30189  CA001108395  19990929    SNWD          51    NaN      O      S
30190  CA001108395  19990930    SNWD          79    NaN      O      S
38912  CA001108395  20080419    SNWD          20    NaN      O      S
55081  CA001108395  20170805    SNWD          10    NaN      M      S

       OBS-TIME
8104        NaN
12989       NaN
17363       NaN
30188       NaN
30189       NaN
30190       NaN
38912       NaN
55081       NaN
                ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  \
619    CA003031092  20121208    SNOW           0    NaN      I      C
646    CA003031092  20121207    SNWD          30    NaN      I      C
647    CA003031092  20121208    SNWD          70    NaN      I      C
2220   CA003031092  20140204    SNOW           2    NaN      I      C
2247   CA003031092  20140203    SNWD           0    NaN      I      C
2248   CA003031092  20140204    SNWD          80    NaN      I      C
3718   CA003031092  20150120    SNOW           0    NaN      I      C
3748   CA003031092  20150119    SNWD          20    NaN      I      C
3749   CA003031092  20150120    SNWD          70    NaN      I      C
11599  CA003031092  20180215    SNOW           0      T      I      C
11626  CA003031092  20180214    SNWD         100    NaN      I      C
11627  CA003031092  20180215    SNWD         170    NaN      I      C
13795  CA003031092  20181213    SNOW           0    NaN      I      C
13825  CA003031092  20181212    SNWD          30    NaN      I      C
13826  CA003031092  20181213    SNWD          90    NaN      I      C
16523  CA003031092  20200109    SNOW           2    NaN      I      C
16553  CA003031092  20200108    SNWD          40    NaN      I      C
16554  CA003031092  20200109    SNWD          70    NaN      I      C
19113  CA003031092  20210107    SNOW           0    NaN      I      C
19114  CA003031092  20210108    SNOW           0    NaN      I      C
19135  CA003031092  20210129    SNOW           0    NaN      I      C
19143  CA003031092  20210106    SNWD          40    NaN      I      C
19144  CA003031092  20210107    SNWD          70    NaN      I      C
19145  CA003031092  20210108    SNWD         100    NaN      I      C
19165  CA003031092  20210128    SNWD          20    NaN      I      C
19166  CA003031092  20210129    SNWD          70    NaN      I      C
19340  CA003031092  20210223    SNOW           0      T      I      C
19367  CA003031092  20210222    SNWD          40    NaN      I      C
19368  CA003031092  20210223    SNWD         140    NaN      I      C
24580  CA003031092  20230311    SNOW          10    NaN      I      C
24610  CA003031092  20230310    SNWD         110    NaN      I      C
24611  CA003031092  20230311    SNWD         200    NaN      I      C
26486  CA003031092  20231228    SNOW           0    NaN      I      C
26509  CA003031092  20231227    SNWD           0      T      I      C
26510  CA003031092  20231228    SNWD          30    NaN      I      C

       OBS-TIME
619         NaN
646         NaN
647         NaN
2220        NaN
2247        NaN
2248        NaN
3718        NaN
3748        NaN
3749        NaN
11599       NaN
11626       NaN
11627       NaN
13795       NaN
13825       NaN
13826       NaN
16523       NaN
16553       NaN
16554       NaN
19113       NaN
19114       NaN
19135       NaN
19143       NaN
19144       NaN
19145       NaN
19165       NaN
19166       NaN
19340       NaN
19367       NaN
19368       NaN
24580       NaN
24610       NaN
24611       NaN
26486       NaN
26509       NaN
26510       NaN
                ID      DATE ELEMENT  DATA_VALUE M-FLAG Q-FLAG S-FLAG  \
22718  CA006106001  20220104    SNOW           0      T      I      C
22748  CA006106001  20220103    SNWD          20    NaN      I      C
22749  CA006106001  20220104    SNWD          50    NaN      I      C
23698  CA006106001  20220521    WSFG        1200    NaN      X      C

       OBS-TIME
22718       NaN
22748       NaN
22749       NaN
23698       NaN

# Metadata

In [41]:
cities_ids = list(map(lambda x: x[:x.find(".")], cities_list))
cities_ids

['CA006158731', 'CA007025251', 'CA001108395', 'CA003031092', 'CA006106001']

In [42]:
station_metadata = "ghcnd-stations.txt"

station_metadata_df = pd.read_fwf(
    f"{base_url}{station_metadata}",
    colspecs=[(0,11), (12,20), (21,30), (31,37), (38,40), (41,71), (72,75), (77,79), (80,85)],
    names=["ID", "LATITUDE", "LONGITUDE", "ELEVATION", "STATE", "NAME", "GSN_FLAG", "HCN_CRN_FLAG", "WMO_ID"]
)

string_cols = station_metadata_df.select_dtypes(include=['object']).columns
station_metadata_df[string_cols] = station_metadata_df[string_cols].apply(lambda x: x.str.strip())
station_metadata_df.info()
station_metadata_df[station_metadata_df["ID"].isin(cities_ids)]

<class 'pandas.DataFrame'>
RangeIndex: 132501 entries, 0 to 132500
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            132501 non-null  str
 1   LATITUDE      132501 non-null  float64
 2   LONGITUDE     132501 non-null  float64
 3   ELEVATION     132501 non-null  float64
 4   STATE         88512 non-null   str
 5   NAME          132501 non-null  str
 6   GSN_FLAG      991 non-null     str
 7   HCN_CRN_FLAG  1452 non-null    str
 8   WMO_ID        7966 non-null    float64
dtypes: float64(4), str(5)
memory usage: 9.1 MB

/var/folders/1f/sv9398xj4s35n39r0h5cb4580000gp/T/ipykernel_39022/760907019.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_cols = station_metadata_df.select_dtypes(include=['object']).columns

,ID,LATITUDE,LONGITUDE,ELEVATION,STATE,NAME,GSN_FLAG,HCN_CRN_FLAG,WMO_ID
24696,CA001108395,49.2000,-123.1833,4.0,BC,VANCOUVER INTL A,NaN,NaN,71892.0
26324,CA003031092,51.1167,-114.0167,1084.0,AB,CALGARY INTL A,NaN,NaN,71877.0
28896,CA006106001,45.3167,-75.6667,114.0,ON,OTTAWA INT'L,NaN,NaN,71628.0
29742,CA006158731,43.6767,-79.6306,173.4,ON,TORONTO INTL A,NaN,NaN,71624.0
30098,CA007025251,45.4706,-73.7408,36.0,QC,MONTREAL INTL A,NaN,NaN,71627.0

In [46]:
station_inventory = "ghcnd-inventory.txt"

station_inventory_df = pd.read_fwf(
    f"{base_url}{station_inventory}",
    colspecs=[(0,11), (12,20), (21,30), (31,35), (36,40), (41,45)],
    names=["ID", "LATITUDE", "LONGITUDE", "ELEMENT", "FIRSTYEAR", "LASTYEAR"]
)

string_cols = station_inventory_df.select_dtypes(include=['object']).columns
station_inventory_df[string_cols] = station_inventory_df[string_cols].apply(lambda x: x.str.strip())
station_inventory_df.info()
station_inventory_df[station_inventory_df["ID"].isin(cities_ids)]

/var/folders/1f/sv9398xj4s35n39r0h5cb4580000gp/T/ipykernel_39022/4054541358.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_cols = station_inventory_df.select_dtypes(include=['object']).columns

<class 'pandas.DataFrame'>
RangeIndex: 782281 entries, 0 to 782280
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ID         782281 non-null  str
 1   LATITUDE   782281 non-null  float64
 2   LONGITUDE  782281 non-null  float64
 3   ELEMENT    782281 non-null  str
 4   FIRSTYEAR  782281 non-null  int64
 5   LASTYEAR   782281 non-null  int64
dtypes: float64(2), int64(2), str(2)
memory usage: 35.8 MB

                 ID  LATITUDE  LONGITUDE ELEMENT  FIRSTYEAR  LASTYEAR
76140   CA001108395   49.2000  -123.1833    TMAX       1957      2025
76141   CA001108395   49.2000  -123.1833    TMIN       1957      2025
76142   CA001108395   49.2000  -123.1833    PRCP       1957      2025
76143   CA001108395   49.2000  -123.1833    SNOW       2013      2024
76144   CA001108395   49.2000  -123.1833    SNWD       1958      2025
76145   CA001108395   49.2000  -123.1833    TAVG       1957      2025
76146   CA001108395   49.2000  -123.1833    WDFG       2015      2024
76147   CA001108395   49.2000  -123.1833    WSFG       2015      2024
85685   CA003031092   51.1167  -114.0167    TMAX       2012      2024
85686   CA003031092   51.1167  -114.0167    TMIN       2012      2024
85687   CA003031092   51.1167  -114.0167    PRCP       2012      2024
85688   CA003031092   51.1167  -114.0167    SNOW       2012      2024
85689   CA003031092   51.1167  -114.0167    SNWD       2012      2024
85690   CA003031092   51.1167  -114.0167    TAVG       2015      2024
85691   CA003031092   51.1167  -114.0167    WDFG       2015      2024
85692   CA003031092   51.1167  -114.0167    WSFG       2015      2024
100324  CA006106001   45.3167   -75.6667    TMAX       2011      2024
100325  CA006106001   45.3167   -75.6667    TMIN       2011      2024
100326  CA006106001   45.3167   -75.6667    PRCP       2011      2024
100327  CA006106001   45.3167   -75.6667    SNOW       2011      2024
100328  CA006106001   45.3167   -75.6667    SNWD       2011      2024
100329  CA006106001   45.3167   -75.6667    TAVG       2015      2024
100330  CA006106001   45.3167   -75.6667    WDFG       2015      2024
100331  CA006106001   45.3167   -75.6667    WSFG       2015      2024
104813  CA006158731   43.6767   -79.6306    TMAX       2013      2024
104814  CA006158731   43.6767   -79.6306    TMIN       2013      2024
104815  CA006158731   43.6767   -79.6306    PRCP       2013      2024
104816  CA006158731   43.6767   -79.6306    SNOW       2013      2024
104817  CA006158731   43.6767   -79.6306    SNWD       2013      2024
104818  CA006158731   43.6767   -79.6306    TAVG       2015      2024
104819  CA006158731   43.6767   -79.6306    WDFG       2015      2024
104820  CA006158731   43.6767   -79.6306    WSFG       2015      2024
106841  CA007025251   45.4706   -73.7408    TMAX       2013      2024
106842  CA007025251   45.4706   -73.7408    TMIN       2013      2024
106843  CA007025251   45.4706   -73.7408    PRCP       2013      2024
106844  CA007025251   45.4706   -73.7408    SNOW       2013      2024
106845  CA007025251   45.4706   -73.7408    SNWD       2013      2024
106846  CA007025251   45.4706   -73.7408    TAVG       2015      2024
106847  CA007025251   45.4706   -73.7408    WDFG       2015      2024
106848  CA007025251   45.4706   -73.7408    WSFG       2015      2024

In [ ]:
country_codes = "ghcnd-countries.txt"

country_codes_df = pd.read_fwf(
    f"{base_url}{country_codes}",
    colspecs=[(0,2), (2,None)],
    names=["Country_Code", "Country_Name"]
)
# string_cols = country_codes_df.select_dtypes(include=['object']).columns
country_codes_df = country_codes_df.apply(lambda x: x.str.strip())
country_codes_df

    Country_Code                 Country_Name
0             AC          Antigua and Barbuda
1             AE         United Arab Emirates
2             AF                  Afghanistan
3             AG                      Algeria
4             AJ                   Azerbaijan
..           ...                          ...
214           WI               Western Sahara
215           WQ  Wake Island [United States]
216           WZ                    Swaziland
217           ZA                       Zambia
218           ZI                     Zimbabwe

[219 rows x 2 columns]

# Try functions

In [ ]:
import yaml
import pandas as pd


# Configuration file
CONFIG_PATH = ""

# NOAA
BASE_URL = "https://www.ncei.noaa.gov/pub/data/ghcn/daily/"
DAILY_OBS = "by_station/"

def load_target_stations(config_path=CONFIG_PATH):
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    return config["stations"]


stations = load_target_stations(config_path=CONFIG_PATH)
print(stations)

[{'city': 'Toronto', 'station_id': 'CA006158731'}, {'city': 'Montreal', 'station_id': 'CA007025251'}, {'city': 'Vancouver', 'station_id': 'CA001108395'}, {'city': 'Calgary', 'station_id': 'CA003031092'}, {'city': 'Ottawa', 'station_id': 'CA006106001'}]

In [7]:
print(type(stations))
for i in stations:
    # print (i)
    print(i["city"])
    print(i["station_id"])
    print()

stations[0]

<class 'list'>
Toronto
CA006158731

Montreal
CA007025251

Vancouver
CA001108395

Calgary
CA003031092

Ottawa
CA006106001

{'city': 'Toronto', 'station_id': 'CA006158731'}

In [4]:
# Fetch daily raw data from NOAA weather
def fetch_station_data(station_id, base_url=BASE_URL, daily_obs=DAILY_OBS):    
    STATION_URL = f"{base_url}{daily_obs}{station_id}.csv.gz" 
    df = pd.read_csv(STATION_URL, compression="gzip", header=None)
    
    return df

# test - delete later
first_city = fetch_station_data(station_id=stations[0]["station_id"])
print(first_city.head(1))

             0         1     2    3    4    5  6   7
0  CA006158731  20130613  TMAX  227  NaN  NaN  C NaN

In [13]:
stations, type(stations)

([{'city': 'Toronto', 'station_id': 'CA006158731'},
  {'city': 'Montreal', 'station_id': 'CA007025251'},
  {'city': 'Vancouver', 'station_id': 'CA001108395'},
  {'city': 'Calgary', 'station_id': 'CA003031092'},
  {'city': 'Ottawa', 'station_id': 'CA006106001'}],
 list)

In [15]:
for station in stations:
    print(station)
    city = station["city"]
    station_id = station["station_id"]
    print(city, station_id)
    print()

{'city': 'Toronto', 'station_id': 'CA006158731'}
Toronto CA006158731

{'city': 'Montreal', 'station_id': 'CA007025251'}
Montreal CA007025251

{'city': 'Vancouver', 'station_id': 'CA001108395'}
Vancouver CA001108395

{'city': 'Calgary', 'station_id': 'CA003031092'}
Calgary CA003031092

{'city': 'Ottawa', 'station_id': 'CA006106001'}
Ottawa CA006106001

In [ ]:
# def fetch_all_stations_data(station_id):
#     station_data_list = []
#     for station in stations:
#         station_id = station["station_id"]
#         station_data_list.append(fetch_station_data(station_id))

#     df = pd.concat(station_data_list)

#     return df

In [20]:
def fetch_all_stations_data(stations):
    station_data_list = []
    # for station in stations:
    #     station_id = station["station_id"]
    #     station_data_list.append(fetch_station_data(station_id))

    # df = pd.concat(station_data_list)
    for i in range(len(stations)):
        print(i)
        station_data_list.append(fetch_station_data(station_id=stations[i]["station_id"]))

    df = pd.concat(station_data_list)
    
    return df

In [21]:
fetch_all_stations_data(stations)

0
1
2

/var/folders/1f/sv9398xj4s35n39r0h5cb4580000gp/T/ipykernel_48332/702482997.py:4: DtypeWarning: Columns (0: 5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(STATION_URL, compression="gzip", header=None)

3
4

                 0         1     2    3    4    5  6   7
0      CA006158731  20130613  TMAX  227  NaN  NaN  C NaN
1      CA006158731  20130614  TMAX  226  NaN  NaN  C NaN
2      CA006158731  20130615  TMAX  258  NaN  NaN  C NaN
3      CA006158731  20130616  TMAX  261  NaN  NaN  C NaN
4      CA006158731  20130617  TMAX  247  NaN  NaN  C NaN
...            ...       ...   ...  ...  ...  ... ..  ..
28439  CA006106001  20240423  WSFG  700  NaN  NaN  C NaN
28440  CA006106001  20240424  WSFG  580  NaN  NaN  C NaN
28441  CA006106001  20240425  WSFG  310  NaN  NaN  C NaN
28442  CA006106001  20240427  WSFG  460  NaN  NaN  C NaN
28443  CA006106001  20240428  WSFG  470  NaN  NaN  C NaN

[180301 rows x 8 columns]

In [28]:
STATION_METADATA = "ghcnd-stations.txt"
STATION_INVENTORY = "ghcnd-inventory.txt"
COUNTRY_CODES = "ghcnd-countries.txt "

def fetch_station_metadata(station_metadata, base_url=BASE_URL):
    df = pd.read_fwf(f"{base_url}{station_metadata}", header=None)
    return df

def fetch_station_inventory(station_inventory, base_url=BASE_URL):
    df = pd.read_fwf(f"{base_url}{station_inventory}", header=None)
    return df

def fetch_county_codes(country_codes, base_url=BASE_URL):
    df = pd.read_fwf(f"{base_url}{country_codes}", header=None)
    return df

In [29]:
station_metadata_df = fetch_station_metadata(station_metadata=STATION_METADATA, base_url=BASE_URL)
station_metadata_df

,0,1,2,3,4,5,6,7
0,ACW00011604,17.1167,-61.7833,10.1,ST JOHNS COOLIDGE FLD,NaN,NaN,NaN
1,ACW00011647,17.1333,-61.7833,19.2,ST JOHNS,NaN,NaN,NaN
2,AE000041196,25.3330,55.5170,34.0,SHARJAH INTER. AIRP,NaN,GSN,41196.0
3,AEM00041194,25.2550,55.3640,10.4,DUBAI INTL,NaN,NaN,41194.0
4,AEM00041217,24.4330,54.6510,26.8,ABU DHABI INTL,NaN,NaN,41217.0
...,...,...,...,...,...,...,...,...
132496,ZI000067969,21.0500,29.3670,861.0,WEST NICHOLSON,NaN,NaN,67969.0
132497,ZI000067975,20.0670,30.8670,1095.0,MASVINGO,NaN,NaN,67975.0
132498,ZI000067977,21.0170,31.5830,430.0,BUFFALO RANGE,NaN,NaN,67977.0
132499,ZI000067983,20.2000,32.6160,1132.0,CHIPINGE,NaN,GSN,67983.0
132500,ZI000067991,22.2170,30.0000,457.0,BEITBRIDGE,NaN,NaN,67991.0

In [ ]:

import pandas as pd

CONFIG_PATH = ""
def load_target_stations(config_path=CONFIG_PATH):
    df = pd.read_csv(config_path)
    
    return df.to_dict(orient='records')

print(load_target_stations(config_path=CONFIG_PATH))

[{'city': 'Toronto', 'station_id': 'CA006158731'}, {'city': 'Montreal', 'station_id': 'CA007025251'}, {'city': 'Vancouver', 'station_id': 'CA001108395'}, {'city': 'Calgary', 'station_id': 'CA003031092'}, {'city': 'Ottawa', 'station_id': 'CA006106001'}]

In [ ]:
import yaml

CONFIG_PATH = ""

def load_target_stations(config_path=CONFIG_PATH):
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    return config["stations"]

print(load_target_stations(config_path=CONFIG_PATH))

[{'city': 'Toronto', 'station_id': 'CA006158731'}, {'city': 'Montreal', 'station_id': 'CA007025251'}, {'city': 'Vancouver', 'station_id': 'CA001108395'}, {'city': 'Calgary', 'station_id': 'CA003031092'}, {'city': 'Ottawa', 'station_id': 'CA006106001'}]